### ISSUE TITLE
Add Home page

### ISSUE THREAD

**Issue by patelyash5208** [patelyash5208/2022_T20_worldcup#1]
Add one picture and Information about T20 world cup

**Comment by Ashish13singh** [comment]
i would like to work on this

**Comment by Ashish13singh** [comment]
![issue #3](https://user-images.githubusercontent.com/114776175/194047204-0aa7e15d-7f25-4eeb-92b3-d8005775f89f.png)

**Comment by patelyash5208** [comment]
please add some margin and padding to text  and change the font use roboto mono font . @Ashish13singh

**Comment by vishal-kacha** [comment]
I can add the margin and padding and change the font.

**Comment by Ashish13singh** [comment]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/114776175/194100415-c5ba9527-9c62-400a-8769-6c603c2b9165.png">

**Comment by patelyash5208** [comment]
Make pull request @Ashish13singh
